# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8460ab59f38b0f4ba7521e9901af6b21ba9c49f546b436fee644993dfa1d5d5289fcc22d6fe1f369fa30ba31af6370e878d8104c94aa7a74e586b128481f9843

test:
  secret_key_base: 8f498907b3568c612b03aae0069ea8d46df98bbc2db9a88a11d76bfa4718f166cd9b7b184186320e1a02c0264940bfde897d134f07d13abaafa24a5e0f99d6f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
